version: '3.3'
services:
  postgres:
    image: postgres:14.1
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=clevertec
  app:
    image: app
    ports:
      - 8080:8080
    build:
      context: .
    depends_on:
      - postgres
    restart: always
    environment:
      - DB_URL=jdbc:postgresql://postgres:5431/clevertec
      - DB_USERNAME=root
      - DB_PASSWORD=root